### ISSUE TITLE
List three reasons for and against using Node.js and JavaScript

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#11]
Go!

**Comment by Jojokats** [comment]
# Advantages Of Node.js
+ Node.js enables developers to write server-side applications in JavaScript. So the developers can use the runtime environment to write both front-end and back-end of a web application in JavaScript, without using any server-side programming language.

+ Delivers Improved Performance: 
Code is executed in a faster and more efficient way. Also, the runtime environment increases the code execution speed significantly by supporting non-blocking I/O operations.

+ Supports Commonly Used Tools: Developers can specify and install project dependencies more efficiently by taking advantage of a robust package manager like npm. Also, option to use grunt as an efficient task runner for the project.

# Disadvantages Of Node.js

+ Lack of Robust Libraries

+ Asynchronous Programming Model: To enhance scalability, Node.js requires programmers to adopt an asynchronous programming approach. Many developers find the asynchronous programming model to be more complicated than linear blocking I/O programming.

+ Not Suitable for Large and Complex Web Applications: At present, Node.js does not support both multi-threaded programming.

**Comment by hammerhead79** [comment]
![nodejs](https://user-images.githubusercontent.com/25584914/30647997-eff7f312-9dea-11e7-8262-eb63e243bae4.png)

**Comment by VernL** [comment]
## Pro's
- JavaScript
  - Specifically for our project team, everyone is familiar with and/or actively learning JavaScript. 
    - Applied learning (opportunity to apply what we learn on a real project).
    - Saves time (It could take a significant amount of time for us all get up and running in another language... I'm looking at you Java!).
    - Facilitate collaboration (everyone in the team will be able to review/understand both front-end and back-end code).
- One of the hottest technologies

**Comment by HanieJ** [comment]
# Pros:

* Its built on JavaScript and has relatively small learning curve.
* Asynchronous nature which has more than one worker thread running and actual JavaScript runs on one thread. It means node doesnt wait for data instead it deals with data as it is available.
* NPM modules: modules and libraries available for almost every possible scenario. Great available documentation. Even we can control the asynchronous nature of the language by using promise calls and asynch libraries to make it behave like synchronized.
* Mostly used for web application development.
* Its data intensive, lightweight and perfect on distributed devices.

# Cons:

* Due to asynchronous nature, working on the logic is little complex.
* Not suitable for high computational programs.
* Callbacks are essential and eventually endup with multiple nested callbacks.

**Comment by RichardLitt** [comment]
Looks like we're going with this!
