### ISSUE TITLE
List three reasons for and against using Java

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#13]
Why should we?

**Comment by Jojokats** [comment]
# Advantages for using Java
+ Simple: Java was designed to be easy to use, write, compile, debug, and learn than other programming languages. Java is much simpler than C++ because Java uses automatic memory allocation and garbage collection.
+ Object-Oriented: Allows you to create modular programs and reusable code.
+ Platform-Independent: Ability to move easily from one computer system to another

# Disadvantages for using Java
+Performance: SIgnificantly slower and more memory-consuming than natively compiled languages such as C or C++.
+Look and feel: The default look and feel of GUI applications written in Java using the Swing toolkit is very different from native applications.
+Single-paradigm language: The addition of static imports in Java 5.0 the procedural paradigm is better accommodated than in earlier versions of Java.

**Comment by HanieJ** [comment]
# Pros:
* One of the most commonly used languages in industry
* Massive amount of libraries! as it has been around for a long time
* Easy debugging thanks to its IDE

# Cons:  
* Evolves very slowly.
* Too verbose: A Hello world needs package, class, static method and the actual printf!
* Long learning curve
* Locks you into static OOP mindset

**Comment by RichardLitt** [comment]
> Locks you into static OOP mindset

I think this is the worst thing for us, at the moment. We want to be dynamic. Let's move away from this language at the moment.
