### ISSUE TITLE
Front-End: List three reasons for and against using AngularJS

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#14]

**Comment by Jojokats** [comment]
# Advantages for using Angular

1- Improved server performance
Because it supports caching and many other processes, Angular reduces burden from server CPUs. It means that the server performs extremely well thanks to reduced traffic and because it only serves static files and responds to the API calls.

2- Two-way data binding
AngularJS facilitates faster and easier data binding which doesn’t require a developer to intervene at all. Referred to as two-way data binding, it ensures that changes made to view are instantly displayed in the model and vice-versa.

3- The MVVM architecture
AngularJS implements Model-View–Controller and Model-View-Viewmodel architectural patterns which lay strong foundations for application performance. With these divisions, the data is separated from design and visual representation which makes even complex web applications easy to manage.

# Disadvantages for using Angular

1- The scopes
Quite layered and arranged hierarchically, scopes can be complex entities to handle if it is your first experience with Angular. One of the most difficult tasks could be debugging the scopes.

2- JavaScript support mandatory
The associated users won’t be able to access your website or web apps if JavaScript is disabled. If there are many such users, you can expect your AngularJS-based web properties to be less useful.
 
3- Difficult features
Directives are difficult to use. In addition, many AngularJS features like dependency injections and factories can be problematic for the more traditional developers.

**Comment by HanieJ** [comment]
![angular](https://qph.ec.quoracdn.net/main-qimg-06a25d4b46bae22b0d583e6e4ee3472b.webp)

**Comment by RichardLitt** [comment]
> Possible time consumption

This is the biggest issue, for me. Also, typeScript and the learning curve. I think we should drop this one.
