### ISSUE TITLE
Front-End: List three reasons for and against using Choo

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#17]

**Comment by Jojokats** [comment]
# Pros

#### Minimal in every aspect
+ Choo's modular core was engineered from the ground up to be smaller and more efficient than every other alternative out there. 
#### No framework lock in
+ Choo operates on raw DOM nodes using an advanced diffing algorithm. Not only is this fast, it also means that all elements you build can be rendered directly on the DOM. Elements built for choo will work as long as the DOM continues to exist.
#### Easy to start with
+ Instead of inventing a new language, Choo relies on vanilla JS and HTML. Combined with its small API and clean architecture this means Choo is easy to get started with, and stays that way as projects grow in scope and humans.

**Comment by RichardLitt** [comment]
> No job demand in Montreal

No job demand anywhere, I think. BUT you would be able to say you know it. I think this might be good as a later project, but not for your first one.
