### ISSUE TITLE
Front-End: List three reasons for and against using VanillaJS

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#18]

**Comment by Jojokats** [comment]
# Advantages for using Vanilla JS
+ The major benefit is that you're the sole master of your code. 
You don't have to wonder how the $.extend() method works of if it may have bugs because you're responsible of every bit of the code you write. 

+ Javascript is executed on the client side.
The code is executed on the user's processor instead of the web server thus saving bandwidth and strain on the web server.

+ Javascript is relatively fast to the end user
As the code is executed on the user's computer, results and processing is completed almost instantly depending on the task as it does not need to be processed in the site's web server and sent back to the user consuming local as well as server bandwidth. 

# Disadvantages for using Vanilla JS

+ Major disadvantage
is that often we don't have enough time to write our code from scratch.

+ Security Issues .
Javascript snippets, once appended onto web pages execute on client servers immediately and therefore can also be used to exploit the user's system. While a certain restriction is set by modern web standards on browsers, malicious code can still be executed complying with the restrictions set.  
+ Javascript rendering varies.
 Different layout engines may render Javascript differently resulting in inconsistency in terms of functionality and interface. While the latest versions of javascript and rendering have been geared towards a universal standard, certain variations still exist.

**Comment by RichardLitt** [comment]
Your second two pros could also apply to a framework. 

Is there _any_ other benefit to writing using vanillajs verse using a framework?

**Comment by HanieJ** [comment]
# PROS:
* It is really fast! (Retrieving DOM element by ID for around 12M Ops/sec)
* Tool to innovate! not only execute
* No special (JSX/React!) syntax to learn!

# CONS:
* Can be perceived as unstructured 
* The wheel already exists, why reinvent it?
* Getting slow with responding to Bo$$/Clients

**Comment by Jojokats** [comment]
# More Pros for using Vanilla JS
+ No special (JSX/React!) syntax to learn 
+ The entire app is in one file, with comments

**Comment by VernL** [comment]
# Pro's
- Could be a good (but cruel) learning experience.
- Could be well suited for a very small/simple project.
- Your friends will think you are cool (or completely insane).

# Con's
- More complex projects would quickly become convoluted.
- It would be extremely difficult to create a responsive/dynamic web app that also provided a good user experience. (although I read somewhere that pretty much anything is possible with a few variables, Booleans and for loops so hey, don't let me stop you!) 
- Not as cool as writing your own programming language and just using that.

**Comment by RichardLitt** [comment]
I would love to have us write vanilla, but I'm not sure it is the best place for us to start. 

> It would be extremely difficult to create a responsive/dynamic web app that also provided a good user experience.

and 

>  often we don't have enough time to write our code from scratch.

are big detractions. 

It would definitely be cool. @Jojokats This doesn't mean that we'd have to write it in one file - we could import from other files, I believe. But yeah. Not great.
