### ISSUE TITLE
Front-end: List a different framework we could use, and three reasons for and against

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#19]
You cannot use: Angular, React, Choo, Vue.js, or vanillaJS. I'd like each of you to write a different front-end framework.

**Comment by HanieJ** [comment]
# Angular
![angular](http://blog.backand.com/wp-content/uploads/2015/04/angular-pros-cons.jpg)

**Comment by RichardLitt** [comment]
Can we have the source for this? It looks a bit old - the suggestion to hold off for 2.0 makes me think it is not up to date.

**Comment by RichardLitt** [comment]
Angular is mentioned in #14. Can we list a different resource? :)

**Comment by HanieJ** [comment]
Src to the other infographic: http://blog.backand.com/pros-and-cons-of-angularjs/
## Humm... I found this one too:
![angular](https://qph.ec.quoracdn.net/main-qimg-06a25d4b46bae22b0d583e6e4ee3472b.webp)

**Comment by RichardLitt** [comment]
Two years is a long time in development. I would consider this out of date. Can you find something from the past six months?

**Comment by HanieJ** [comment]
I am deleting the old ones: Here are the pros and cons:

# Pros:
* DOM manipulation

Unlike other popular JavaScript frameworks, Angular conveniently relieves the developer of actively manipulating DOM (Document Object Model), all thanks to its two-way data binding approach. It means that the developer saves time and efforts to code, translate and update the DOM elements.

* Responsive web

There’s nothing better than arranging an outstanding end-user experience and AngularJS makes it possible by letting responsive, fast-loading and seamlessly-navigating websites and apps.

* Highly testable products

One of the underlying aspects of Angular is that it builds highly testable websites and applications. By allowing unit testing and end-to-end testing, it makes testing and debugging much simpler than you can imagine. Dependency injections, for example, allow various components to be isolated and mocked. Protractor, Jasmine and Karma are other unique testing tools that the framework offers.

# Cons:
* Difficult learning

Rather than following a straight learning graph, you may have to face great difficulty in getting adapted to the framework. Moreover, the limited documentation available may further affect the learning process. However, the day-by-day extending community is making it easier.

* Inexperience with MVC

If you are a developer who follows the traditional approach and are completely unfamiliar with the Model-View-Controller architectural patterns, using Angular can be extremely time-consuming. In case you have strict deadlines to meet, this might not be the right way to go. A solution however could be to hire some expert if you wish to unlock the framework’s benefits.

* Possible time consumption

The browser may take time to render pages of websites and applications designed using the framework. It may happen because the browsers would be overloaded to perform additional tasks like DOM manipulation. However, this drawback is limited only to the old computers and devices. The modern ones, especially the mobile devices, don’t find it challenging at all.

[src](https://jaxenter.com/the-pros-and-cons-of-choosing-angularjs-124850.html)

**Comment by VernL** [comment]
# Electron: Build cross platform desktop apps with JavaScript, HTML, and CSS 
Pro's
- Native desktop apps! I don't know why we need this but still cool! 
- Compatible with IOS, Windows and Linux.
- Includes all of node JS built in modules. 
- Many popular softwares run on Electron including Slack and wordpess.com.

Con's
- Bloated and large files even for simple web apps. 
- Not truly native (performance issues, some users report a poor user experience)
- Probably not the most logical choice for a web app.

Electron Intro [Video](https://www.youtube.com/watch?v=8YP_nOCO-4Q&feature=youtu.be) 4 minutes

**Comment by HanieJ** [comment]
Poof. I misread the title! I hope this would be right ~.~

# POLYMER:
- Polymer believes in leveraging the browsers “Native” technologies rather than relying on some increasingly complex custom JavaScript libraries.
- Polymer web development is always about creating only elements.
- The polymer provides the ability to compose enclosed JS, CSS, and HTML as Custom elements.
- Polymer elements provide templating and bi-directional data binding. It also provides new functionality such as Shadow DOM which enables the encapsulation of CSS.
- Quick: The Polymer is a new library which is three times faster on Chrome, four times faster on Safari. Also, it is ready to be used in production applications and believed to be easier for developers to produce feature-rich applications and websites.

# CONS:
- It is not entirely clear that how to organize larger applications.
- Dependency errors and pointing to a different version of dependencies.
- Downloading of entire library and Polyfills.
- Lack of server side rendering.

**Comment by RichardLitt** [comment]
###  Ember

> Very steep learning curve. Better learn javascript at first, then start learning Ember which may take some time
> Core team is very slow in their feature development and last several versions of Ember were mostly minor releases that mostly brought nothing new.

These are big issues. 

> There are pros and cons to both approaches, but those who want everything to just work well together will love Ember!

This sounds like marketing material :(. I'm not sure any of the pros listed there are really true or helpful. Why is it dependable, for instance? Also, in software, "everything just works well" has never been the case, in my experience, sadly. Maybe I'm wrong!

### Electron

Would be super fun! But out of scope for this project.

### Polymer

This would also be super fun! But "It is not entirely clear that how to organize larger applications." is a big enough issue for me to steer away from this for now.
